openapi: 3.0.0
info:
  title: My API
  description: API documentation for my Express application
  version: 1.0.0
paths:
  /v1/auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterPayload"
      responses:
        "200":
          description: Registration successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthResponse"
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error

  /v1/auth/login:
    post:
      summary: Login a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginPayload"
      responses:
        "200":
          description: Login successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthResponse"
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error

  /v1/auth/me:
    get:
      summary: Get the current user
      security:
        - bearerAuth: []
      responses:
        "200":
          description: User data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error

  /v1/endpoint:
    post:
      summary: Save a value
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SaveValuePayload"
      responses:
        "200":
          description: Value saved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Value"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error

    get:
      summary: Get a value
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Retrieved value or null
          content:
            application/json:
              schema:
                type: string
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error

components:
  schemas:
    RegisterPayload:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password

    LoginPayload:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password

    AuthResponse:
      type: object
      properties:
        access_token:
          type: string

    User:
      type: object
      properties:
        id:
          type: string
        username:
          type: string
        registered_at:
          type: string
          format: date-time

    SaveValuePayload:
      type: object
      properties:
        value:
          type: string
        expires_at:
          type: string
          format: date-time
      required:
        - value
        - expires_at

    Value:
      type: object
      properties:
        id:
          type: string
        value:
          type: string
        expires_at:
          type: string
          format: date-time

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
